-- Phase 5: teacher panel.

-- "Resumen para el docente": generated by AI from aggregated findings (never names or chats) and
-- cached by a hash of those findings and the prompt version, so the same data is summarised once.
-- section_id is null for the demo section. Only the server (service role) reads and writes it, after
-- checking that the teacher owns the section; there are no policies for anon or authenticated.
create table public.teacher_summaries (
  key text primary key check (char_length(key) = 64),
  section_id uuid references public.sections (id) on delete cascade,
  summary jsonb not null,
  model text,
  created_at timestamptz not null default now()
);
create index teacher_summaries_section_idx on public.teacher_summaries (section_id, created_at desc);
alter table public.teacher_summaries enable row level security;
revoke all on public.teacher_summaries from anon, authenticated;

-- The panel lists the latest accesses to a section.
create index if not exists teacher_audit_log_section_idx on public.teacher_audit_log (section_id, created_at desc);
